project_id = "oucnvrfbvqxbazlvvgwn"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-parent-password]
verify_jwt = false


[auth]
enable_anonymous_sign_ins = false
