// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msterrctetotalrsvjye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdGVycmN0ZXRvdGFscnN2anllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MzU3MzEsImV4cCI6MjA5MTMxMTczMX0.FioqNiIQkZlMd31cycSjcNG3OFOoEQxUQ8vSgRPcwrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});